# Mise à jour des adresses de test

## Imports

In [1]:
import os
from datetime import datetime
from pathlib import Path

import polars as pl
from IPython.display import display
from polars.dataframe.frame import DataFrame

## Variables

In [2]:
EXCEL_PATH = r"C:\Users\denis.iglesias\OneDrive - HESSO\01 Institution\02 Projets\00 Archive\03 ECS-Optiwatt eco21-SIG"

In [3]:
# search in EXCEL_PATH in all its sub-folders for the files that are excel
excel_files: list[str] = []
for root, dirs, files in os.walk(EXCEL_PATH):
    for filename in files:
        if filename.endswith(".xlsx"):
            excel_files.append(os.path.join(root, filename))

# Remove certain paths that contains certain keywords
exclude_keywords: list[str] = ["99 Ventilation", "06_cours_python", "sitg"]
excel_files: list[str] = [
    f for f in excel_files if not any(keyword in f for keyword in exclude_keywords)
]

display(f"Found {len(excel_files)} files in {EXCEL_PATH}")
display(excel_files)

'Found 107 files in C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG'

['C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\00 Ancien\\Base_donnees v5.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\00 Ancien\\Base_donnees v6.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\00 Ancien\\ECO21_ECS_PME_Analyse disperison et moyennes v2_EBP.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\00 Ancien\\ECO21_ECS_PME_Analyse disperison et moyennes v3_EBP.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\00 Ancien\\Tableau de suivi ECS Optiwatt 2019-20 v11.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\00 Ancien\\Tableau de suivi ECS Optiwatt 2019-20 v12.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\00 Ancien\\Tableau de suivi ECS Optiwatt 2019-20 v12_ancien.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\00 Ancien\\test_ECS_macro_v1.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\00 Ancien\\20200519\\20200504 Reporting ECS 2018-20 Calcul cas selectionnes EBP.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\00 Ancien\\20200519\\DEI_20200504 Reporting ECS 2018-20 Calcul cas selectionnes EBP.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\00 Ancien\\20200519\\DEI_ECO21_ECS_PME_Analyse disperison et moyennes v2_EBP.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\00 Ancien\\20200519\\EBP_v4.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\00 Ancien\\20200519\\EBP_v5_test.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\00 Ancien\\20200519\\Base de données\\Base_donnees v5.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\00 Ancien\\20200519\\Base de données\\Base_donnees v6.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\00 Ancien\\20200519\\Base de données\\ECO21_ECS_PME_Analyse disperison et moyennes v2_EBP.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\00 Ancien\\20200519\\Base de données\\Minergie.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\00 Ancien\\20200519\\Base de données\\Tableau de suivi ECS Optiwatt 2019-20 v11.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\00 Ancien\\20200519\\Base de données\\Tableau de suivi ECS Optiwatt 2019-20 v12.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\00 Ancien\\20200519\\Base de données\\Denis\\Base_donnees v5.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\00 Ancien\\20200519\\Base de données\\Denis\\Base_donnees v6.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\00 Ancien\\20200519\\Base de données\\Denis\\ECO21_ECS_PME_Analyse disperison et moyennes v2_EBP.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\00 Ancien\\20200519\\Base de données\\Denis\\Minergie.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\00 Ancien\\20200519\\Base de données\\Denis\\Tableau de suivi ECS Optiwatt 2019-20 v11.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\00 Ancien\\20200519\\Base de données\\Denis\\Tableau de suivi ECS Optiwatt 2019-20 v12.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\00 Ancien\\20200519\\Base de données\\Final\\Base_donnees v6.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\00 Ancien\\20200519\\Base de données\\Final\\Tableau de suivi ECS Optiwatt 2019-20 v12.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\00 Ancien\\20200519\\Base de données\\Final\\Reporting\\20200320 Tableau reporting ECS 2018-2019.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\00 Ancien\\20200519\\Base de données\\Final\\Reporting\\Base_donnees v6_valeurs.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\00 Ancien\\20200519\\Base de données\\Final\\Reporting\\ECO21_ECS_PME_Analyse disperison et moyennes v3_EBP.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\00 Ancien\\20201109\\Base_donnees v6.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\00 Ancien\\20201109\\ECO21_ECS_PME_Analyse disperison et moyennes v3_EBP.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\00 Ancien\\20201109\\Tableau de suivi ECS Optiwatt 2019-20 v12.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\00 Ancien\\20201109\\Original\\Base_donnees v6.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\00 Ancien\\20201109\\Original\\ECO21_ECS_PME_Analyse disperison et moyennes v3_EBP.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\00 Ancien\\20201109\\Original\\Tableau de suivi ECS Optiwatt 2019-20 v12.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\01 Administratif\\01 Mandat\\20210128\\20210120 Descriptif Mandat ECS HEPIA.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\01 Administratif\\01 Mandat\\20210201\\20210120 Descriptif Mandat ECS HEPIA_v2.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\01 Administratif\\01 Mandat\\20210312\\20210120 Descriptif Mandat ECS HEPIA_v3.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\01 Administratif\\01 Mandat\\20210317\\20210120 Descriptif Mandat ECS HEPIA_v4.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\01 Administratif\\01 Mandat\\20230703\\2023_Descriptif Mandat ECS HEPIA_v1.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\01 Administratif\\01 Mandat\\20240709\\2023_Descriptif Mandat ECS HEPIA_v1.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\01 Administratif\\01 Mandat\\20251016\\2023_Descriptif Mandat ECS HEPIA_v1.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\01 Administratif\\01 Mandat\\20251016\\00 Archive\\2023_Descriptif Mandat ECS HEPIA_v1.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\01 Administratif\\02 Heures\\Mandat 2022\\Clockify_Time_Report_Detailed_mandat_2022.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\02 Tableaux\\00 Ancien\\20200504 Reporting ECS 2018-20 Calcul cas selectionnes EBP.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\02 Tableaux\\00 Ancien\\ECO21_ECS_PME_Analyse disperison et moyennes v3_EBP.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\02 Tableaux\\00 Ancien\\Minergie.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\02 Tableaux\\00 Ancien\\Tableau de suivi ECS Optiwatt 2019-20 v12_valeurs.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\02 Tableaux\\00 Ancien\\Tableau de suivi ECS Optiwatt 2019-20 v13.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\02 Tableaux\\00 Ancien\\Tableau de suivi ECS Optiwatt 2019-20 v14.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\02 Tableaux\\00 Ancien\\Tableau de suivi ECS Optiwatt 2019-20 v15.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\02 Tableaux\\00 Ancien\\Tableau de suivi ECS Optiwatt 2019-20 v16.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\02 Tableaux\\00 Ancien\\Tableau de suivi ECS Optiwatt 2019-20 v17.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\02 Tableaux\\01 20210420 séance travail SIG jour 1 et 2\\Tableau de suivi ECS Optiwatt 2019-21.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\02 Tableaux\\01 20210420 séance travail SIG jour 1 et 2\\00 Originaux\\Tableau de suivi ECS Optiwatt 2019-21.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\02 Tableaux\\01 20210420 séance travail SIG jour 1 et 2\\00 Originaux\\Fichier de saisie\\2020\\01 Janvier - 20200007\\Tableau Eau Sanitaire Janvier.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\02 Tableaux\\01 20210420 séance travail SIG jour 1 et 2\\00 Originaux\\Fichier de saisie\\2020\\02 Février - 20200015\\Tableau Installation Fevrier 2020.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\02 Tableaux\\01 20210420 séance travail SIG jour 1 et 2\\00 Originaux\\Fichier de saisie\\2020\\03 Mars - 20200022\\Tableau Installation mars.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\02 Tableaux\\01 20210420 séance travail SIG jour 1 et 2\\00 Originaux\\Fichier de saisie\\2020\\04 Juillet - 20200028\\Tableau Juillet ECS.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\02 Tableaux\\01 20210420 séance travail SIG jour 1 et 2\\00 Originaux\\Fichier de saisie\\2020\\05 Août - 20200034\\Tableau Petites Installation Aout.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\02 Tableaux\\01 20210420 séance travail SIG jour 1 et 2\\00 Originaux\\Fichier de saisie\\2020\\09 Septembre - 20200042\\Tableau Septembre.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\02 Tableaux\\01 20210420 séance travail SIG jour 1 et 2\\00 Originaux\\Fichier de saisie\\2020\\10 octobre - 20200052\\Tableau Octobre.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\02 Tableaux\\01 20210420 séance travail SIG jour 1 et 2\\00 Originaux\\Fichier de saisie\\2020\\11 Novembre - 20200061\\Petites Installations Novembre.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\02 Tableaux\\01 20210420 séance travail SIG jour 1 et 2\\00 Originaux\\Fichier de saisie\\2021\\01 - Janvier - 2021007\\Tableau Janvier 2021.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\02 Tableaux\\01 20210420 séance travail SIG jour 1 et 2\\00 Originaux\\Fichier de saisie\\2021\\02 - Février - 2021015\\Tableau ESC Fev.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\02 Tableaux\\03 20210927 Jour 3\\EGID_Adresses.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\02 Tableaux\\03 20210927 Jour 3\\EGID_adresse_spotfire.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\02 Tableaux\\03 20210927 Jour 3\\00 Original\\20210528_ECS_ARO.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\02 Tableaux\\03 20210927 Jour 3\\00 Original\\Copie de 20210531_Fichier ECS_Acacias.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\02 Tableaux\\03 20210927 Jour 3\\00 Original\\EGID_Adresses.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\02 Tableaux\\04 20211011 Jour 4\\20210528_ECS_ARO.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\02 Tableaux\\04 20211011 Jour 4\\20211011 Copie de Tableau de suivi ECS Optiwatt 2019-21.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\02 Tableaux\\04 20211011 Jour 4\\ECS_tableau_saisie_prestataire_PaP_Petites.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\02 Tableaux\\04 20211011 Jour 4\\Test.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\02 Tableaux\\04 20211011 Jour 4\\00 Original\\20210528_ECS_ARO.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\02 Tableaux\\04 20211011 Jour 4\\00 Original\\20211011 Copie de Tableau de suivi ECS Optiwatt 2019-21.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\02 Tableaux\\05 20220120 Jour 5\\Copie de Tableau de suivi ECS Optiwatt 2019-21.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\02 Tableaux\\05 20220120 Jour 5\\Test.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\02 Tableaux\\05 20220120 Jour 5\\00 Original\\Copie de Tableau de suivi ECS Optiwatt 2019-21.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\02 Tableaux\\05 20220120 Jour 5\\00 Original\\Tableau decembre 2021 SIG.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\02 Tableaux\\06 20220304 Jour 6\\Proposition tableau calcul.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\02 Tableaux\\08 MAJ septembre 2022\\Tableau de suivi ECS Optiwatt 2019-21.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\02 Tableaux\\08 MAJ septembre 2022\\Tableau de suivi ECS Optiwatt 2019-21_modifie.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\02 Tableaux\\09 MAJ février 2023\\Tableau de suivi ECS Optiwatt 2019-21.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\02 Tableaux\\09 MAJ février 2023\\00 Original\\DERNIER_INDICE.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\02 Tableaux\\09 MAJ février 2023\\00 Original\\Tableau de suivi ECS Optiwatt 2019-21.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\02 Tableaux\\10 mandat 2023-2024\\00 Ancien\\test_adresses.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\02 Tableaux\\10 mandat 2023-2024\\01 Holmes place analyse\\20220930-dee-pae10113-holmes-places.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\02 Tableaux\\10 mandat 2023-2024\\01 Holmes place analyse\\Analyse.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\02 Tableaux\\10 mandat 2023-2024\\02 Courriel du 2023-08-24\\Export ECS_SEMESTRE 2023_1.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\02 Tableaux\\10 mandat 2023-2024\\02 Courriel du 2023-08-24\\00 Original\\Export ECS_SEMESTRE 2023_1.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\02 Tableaux\\10 mandat 2023-2024\\03 Courriel du 2024-01-09\\Tableau de suivi ECS Optiwatt 2023.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\02 Tableaux\\11 mandat 2024-2025\\2024S1\\01 Envoi SIG admin\\Tableau de suivi ECS Optiwatt 2024.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\02 Tableaux\\11 mandat 2024-2025\\2024S1\\01 Envoi SIG admin\\01 Original\\Tableau de suivi ECS Optiwatt 2024.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\02 Tableaux\\11 mandat 2024-2025\\2024S2\\01 Envois SIG admin\\Tableau de suivi ECS Optiwatt 2019-24.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\02 Tableaux\\11 mandat 2024-2025\\2024S2\\01 Envois SIG admin\\01 Original\\Tableau de suivi ECS Optiwatt 2019-24.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\02 Tableaux\\11 mandat 2024-2025\\2024S2\\01 Envois SIG admin\\01 Original\\Tableau de suivi ECS Optiwatt 2024_v2.xlsx',
 'C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\02 Tableaux\\12 mandat 2025-2026\\saisi par support\\Tableau de suivi ECS Optiwatt 2025.xlsx',

In [4]:
"""
Read every sheet of every Excel file, auto-detecting the header row per sheet
(since it is not always the first row), then concatenate everything with
diagonal_relaxed (union of columns, nulls for missing, common supertype for
mismatched dtypes).
"""


def is_sequential_index_row(row: tuple) -> bool:
    """
    Detect a manually-typed row of sequential column numbers (1, 2, 3, ...)
    sometimes placed above the real header as a numbering aid. Such a row is
    fully populated and all-unique, so it otherwise passes as a false-positive
    header.
    """
    try:
        as_ints = [int(v) for v in row]
    except (TypeError, ValueError):
        return False
    return as_ints == list(range(1, len(row) + 1))


def detect_header_row(raw: pl.DataFrame, max_scan_rows: int = 15) -> int:
    """
    Guess which row (0-indexed) holds the column headers.
    Heuristic: a header row is fully populated (no nulls) and has no
    duplicate values, since real headers are distinct labels. We scan the
    first `max_scan_rows` rows and pick the first one matching that pattern,
    skipping sequential numbering rows (1, 2, 3, ...) that would otherwise
    look like a valid header.
    Falls back to row 0 if nothing matches (e.g. sheet truly has no junk rows).
    """
    n_scan = min(max_scan_rows, raw.height)
    for i in range(n_scan):
        row = raw.row(i)
        non_null = [v for v in row if v is not None]
        if (
            len(non_null) == len(row)
            and len(set(non_null)) == len(non_null)
            and not is_sequential_index_row(row)
        ):
            return i
    return 0


def promote_header(raw: pl.DataFrame, header_idx: int) -> pl.DataFrame:
    """Rename columns using the detected header row, drop rows up to and including it."""
    header_values = raw.row(header_idx)
    # Fallback names for any blank header cells, avoid duplicate names
    seen: dict[str, int] = {}
    new_names = []
    for i, v in enumerate(header_values):
        name = str(v) if v is not None else f"col_{i}"
        if name in seen:
            seen[name] += 1
            name = f"{name}_{seen[name]}"
        else:
            seen[name] = 0
        new_names.append(name)

    df = raw.slice(header_idx + 1, raw.height - header_idx - 1)
    df.columns = new_names
    return df


def read_raw_sheets(path: str) -> dict[str, pl.DataFrame]:
    """
    Read all sheets of a file, raw (no header assumed).
    calamine is tried first (fast), falling back to openpyxl (slower, more
    tolerant) if calamine chokes on formula-error cells like #NAME?, #REF!, etc.
    raise_if_empty=False so genuinely empty sheets return an empty frame
    instead of raising NoDataError.
    """
    try:
        return pl.read_excel(
            source=path,
            sheet_id=0,
            engine="calamine",
            has_header=False,
            raise_if_empty=False,
        )
    except Exception as calamine_error:
        try:
            return pl.read_excel(
                source=path,
                sheet_id=0,
                engine="openpyxl",
                has_header=False,
                raise_if_empty=False,
            )
        except Exception as openpyxl_error:
            raise RuntimeError(
                f"calamine failed ({calamine_error}); "
                f"openpyxl fallback also failed ({openpyxl_error})"
            ) from openpyxl_error


def read_all_excel(paths: list[str]) -> list[pl.DataFrame]:
    """Read all sheets of all given Excel files, auto-fixing header row per sheet."""
    frames: list[pl.DataFrame] = []
    errors: list[tuple[str, str]] = []

    for path in paths:
        try:
            raw_sheets = read_raw_sheets(path)
        except Exception as e:
            # Include exception type so future failures are easier to diagnose at a glance
            errors.append((path, f"{type(e).__name__}: {e}"))
            continue

        for sheet_name, raw in raw_sheets.items():
            if raw.height == 0 or raw.width == 0:
                continue
            header_idx = detect_header_row(raw)
            df = promote_header(raw, header_idx)

            # Tag origin, including detected header row for traceability/debugging
            df = df.with_columns(
                pl.lit(Path(path).name).alias("source_file"),
                pl.lit(sheet_name).alias("source_sheet"),
                pl.lit(header_idx).alias("header_row_detected"),
            )
            frames.append(df)

    if errors:
        display(f"Failed to read {len(errors)} file(s):")
        for path, msg in errors:
            display(f"  {path}: {msg}")

    return frames


def concat_safely(frames: list[pl.DataFrame], batch_size: int = 20) -> pl.DataFrame:
    """
    Concatenate frames with diagonal_relaxed in batches.
    Batching avoids a known crash when column counts differ too much
    across a single very large concat call.
    """
    if not frames:
        raise ValueError("No frames to concatenate.")

    batches: list[pl.DataFrame] = []
    for i in range(0, len(frames), batch_size):
        chunk = frames[i : i + batch_size]
        batches.append(pl.concat(chunk, how="diagonal_relaxed"))

    return pl.concat(batches, how="diagonal_relaxed")


# --- Run ---
frames = read_all_excel(excel_files)
display(f"Loaded {len(frames)} sheet(s) from {len(excel_files)} file(s)")

# Sanity check: see which header rows were detected, worth a quick eyeball
header_summary = (
    pl.concat(
        [
            f.select("source_file", "source_sheet", "header_row_detected").head(1)
            for f in frames
        ],
        how="diagonal_relaxed",
    )
    if frames
    else None
)
display(header_summary)

df_all = concat_safely(frames)
display(f"Final shape: {df_all.shape}")
display(df_all)

c:\Users\denis.iglesias\Documents\GitHub\geocoder-service\.venv\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)
Could not determine dtype for column 90, falling back to string
Could not determine dtype for column 1, falling back to string
Could not determine dtype for column 3, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 5, falling back to string
Could not determine dtype for column 7, falling back to string
Could not determine dtype for column 1, falling back to string
Could not determine dtype for column 2, falling back to string
Could not determine dtype for column 90, falling back to string
Could not determine dtype for column 1, falling back to string
Could not determine dtype for column 3, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 5, falling back to string
Could not determine dtype for column 7, falling back to string
Could not determine dtype for column 1, falling back to string
Could not determine dtype for column 2, falling back to string
Could not determine dtype for column 3, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 5, falling back to string
Could not determine dtype for column 6, falling back to string
Could not determine dtype for column 3, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 5, falling back to string
Could not determine dtype for column 6, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 15, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 15, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 15, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 15, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 15, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 15, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 15, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 15, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 15, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 15, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 15, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 15, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 15, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 15, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 15, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 15, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 15, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 15, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 15, falling back to string
Could not determine dtype for column 6, falling back to string
Could not determine dtype for column 7, falling back to string
Could not determine dtype for column 8, falling back to string
Could not determine dtype for column 1, falling back to string
Could not determine dtype for column 3, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 5, falling back to string
Could not determine dtype for column 7, falling back to string
Could not determine dtype for column 1, falling back to string
Could not determine dtype for column 2, falling back to string
Could not determine dtype for column 90, falling back to string
Could not determine dtype for column 1, falling back to string
Could not determine dtype for column 3, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 5, falling back to string
Could not determine dtype for column 7, falling back to string
Could not determine dtype for column 1, falling back to string
Could not determine dtype for column 2, falling back to string
Could not determine dtype for column 6, falling back to string
Could not determine dtype for column 7, falling back to string
Could not determine dtype for column 8, falling back to string
Could not determine dtype for column 1, falling back to string
Could not determine dtype for column 3, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 5, falling back to string
Could not determine dtype for column 7, falling back to string
Could not determine dtype for column 1, falling back to string
Could not determine dtype for column 2, falling back to string
Could not determine dtype for column 90, falling back to string
Could not determine dtype for column 1, falling back to string
Could not determine dtype for column 3, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 5, falling back to string
Could not determine dtype for column 7, falling back to string
Could not determine dtype for column 1, falling back to string
Could not determine dtype for column 2, falling back to string
Could not determine dtype for column 90, falling back to string
Could not determine dtype for column 1, falling back to string
Could not determine dtype for column 3, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 5, falling back to string
Could not determine dtype for column 7, falling back to string
Could not determine dtype for column 1, falling back to string
Could not determine dtype for column 3, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 5, falling back to string
Could not determine dtype for column 7, falling back to string
Could not determine dtype for column 6, falling back to string
Could not determine dtype for column 7, falling back to string
Could not determine dtype for column 6, falling back to string
Could not determine dtype for column 7, falling back to string
Could not determine dtype for column 8, falling back to string
Could not determine dtype for column 10, falling back to string
Could not determine dtype for column 11, falling back to string
Could not determine dtype for column 3, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 5, falling back to string
Could not determine dtype for column 6, falling back to string
Could not determine dtype for column 7, falling back to string
Could not determine dtype for column 1, falling back to string
Could not determine dtype for column 3, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 5, falling back to string
Could not determine dtype for column 7, falling back to string
Could not determine dtype for column 1, falling back to string
Could not determine dtype for column 3, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 5, falling back to string
Could not determine dtype for column 7, falling back to string
Could not determine dtype for column 1, falling back to string
Could not determine dtype for column 3, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 5, falling back to string
Could not determine dtype for column 7, falling back to string
Could not determine dtype for column 1, falling back to string
Could not determine dtype for column 3, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 5, falling back to string
Could not determine dtype for column 7, falling back to string
Could not determine dtype for column 1, falling back to string
Could not determine dtype for column 3, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 5, falling back to string
Could not determine dtype for column 7, falling back to string
Could not determine dtype for column 50, falling back to string
Could not determine dtype for column 60, falling back to string
Could not determine dtype for column 30, falling back to string
Could not determine dtype for column 40, falling back to string
Could not determine dtype for column 50, falling back to string
Could not determine dtype for column 44, falling back to string
Could not determine dtype for column 54, falling back to string
Could not determine dtype for column 1, falling back to string
Could not determine dtype for column 3, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 5, falling back to string
Could not determine dtype for column 7, falling back to string
Could not determine dtype for column 50, falling back to string
Could not determine dtype for column 60, falling back to string
Could not determine dtype for column 30, falling back to string
Could not determine dtype for column 40, falling back to string
Could not determine dtype for column 50, falling back to string
Could not determine dtype for column 44, falling back to string
Could not determine dtype for column 54, falling back to string
Could not determine dtype for column 1, falling back to string
Could not determine dtype for column 3, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 5, falling back to string
Could not determine dtype for column 7, falling back to string
Could not determine dtype for column 1, falling back to string
Could not determine dtype for column 3, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 5, falling back to string
Could not determine dtype for column 7, falling back to string
Could not determine dtype for column 1, falling back to string
Could not determine dtype for column 3, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 5, falling back to string
Could not determine dtype for column 7, falling back to string
Could not determine dtype for column 1, falling back to string
Could not determine dtype for column 3, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 5, falling back to string
Could not determine dtype for column 7, falling back to string
Could not determine dtype for column 29, falling back to string
Could not determine dtype for column 1, falling back to string
Could not determine dtype for column 3, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 5, falling back to string
Could not determine dtype for column 7, falling back to string
Could not determine dtype for column 29, falling back to string
Could not determine dtype for column 1, falling back to string
Could not determine dtype for column 3, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 5, falling back to string
Could not determine dtype for column 7, falling back to string
Could not determine dtype for column 29, falling back to string
Could not determine dtype for column 1, falling back to string
Could not determine dtype for column 3, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 5, falling back to string
Could not determine dtype for column 7, falling back to string
Could not determine dtype for column 29, falling back to string
Could not determine dtype for column 1, falling back to string
Could not determine dtype for column 3, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 5, falling back to string
Could not determine dtype for column 7, falling back to string
Could not determine dtype for column 29, falling back to string
Could not determine dtype for column 1, falling back to string
Could not determine dtype for column 3, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 5, falling back to string
Could not determine dtype for column 7, falling back to string
Could not determine dtype for column 1, falling back to string
Could not determine dtype for column 3, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 5, falling back to string
Could not determine dtype for column 7, falling back to string
Could not determine dtype for column 5, falling back to string
Could not determine dtype for column 5, falling back to string
Could not determine dtype for column 1, falling back to string
Could not determine dtype for column 2, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 5, falling back to string
Could not determine dtype for column 6, falling back to string
Could not determine dtype for column 5, falling back to string
Could not determine dtype for column 5, falling back to string
Could not determine dtype for column 50, falling back to string
Could not determine dtype for column 60, falling back to string
Could not determine dtype for column 41, falling back to string
Could not determine dtype for column 51, falling back to string
Could not determine dtype for column 44, falling back to string
Could not determine dtype for column 54, falling back to string
Could not determine dtype for column 1, falling back to string
Could not determine dtype for column 3, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 5, falling back to string
Could not determine dtype for column 7, falling back to string
Could not determine dtype for column 1, falling back to string
Could not determine dtype for column 2, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 5, falling back to string
Could not determine dtype for column 6, falling back to string
Could not determine dtype for column 5, falling back to string
Could not determine dtype for column 5, falling back to string
Could not determine dtype for column 50, falling back to string
Could not determine dtype for column 60, falling back to string
Could not determine dtype for column 41, falling back to string
Could not determine dtype for column 51, falling back to string
Could not determine dtype for column 44, falling back to string
Could not determine dtype for column 54, falling back to string
Could not determine dtype for column 1, falling back to string
Could not determine dtype for column 3, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 5, falling back to string
Could not determine dtype for column 7, falling back to string
Could not determine dtype for column 50, falling back to string
Could not determine dtype for column 60, falling back to string
Could not determine dtype for column 41, falling back to string
Could not determine dtype for column 51, falling back to string
Could not determine dtype for column 44, falling back to string
Could not determine dtype for column 54, falling back to string
Could not determine dtype for column 1, falling back to string
Could not determine dtype for column 3, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 5, falling back to string
Could not determine dtype for column 7, falling back to string
Could not determine dtype for column 50, falling back to string
Could not determine dtype for column 60, falling back to string
Could not determine dtype for column 41, falling back to string
Could not determine dtype for column 51, falling back to string
Could not determine dtype for column 44, falling back to string
Could not determine dtype for column 54, falling back to string
Could not determine dtype for column 1, falling back to string
Could not determine dtype for column 3, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 5, falling back to string
Could not determine dtype for column 7, falling back to string
Could not determine dtype for column 29, falling back to string
Could not determine dtype for column 1, falling back to string
Could not determine dtype for column 3, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 5, falling back to string
Could not determine dtype for column 7, falling back to string
Could not determine dtype for column 50, falling back to string
Could not determine dtype for column 60, falling back to string
Could not determine dtype for column 41, falling back to string
Could not determine dtype for column 51, falling back to string
Could not determine dtype for column 44, falling back to string
Could not determine dtype for column 54, falling back to string
Could not determine dtype for column 1, falling back to string
Could not determine dtype for column 3, falling back to string

'Failed to read 1 file(s):'

'  C:\\Users\\denis.iglesias\\OneDrive - HESSO\\01 Institution\\02 Projets\\00 Archive\\03 ECS-Optiwatt eco21-SIG\\02 Tableaux\\00 Ancien\\Tableau de suivi ECS Optiwatt 2019-20 v13.xlsx: RuntimeError: calamine failed (calamine cell error: #NAME?\nContext:\n    0: could not determine dtype for column __UNNAMED__44\n); openpyxl fallback also failed (Series name must be a string)'

'Loaded 509 sheet(s) from 107 file(s)'

shape: (509, 3)
┌─────────────────────────────┬───────────────────┬─────────────────────┐
│ source_file                 ┆ source_sheet      ┆ header_row_detected │
│ ---                         ┆ ---               ┆ ---                 │
│ str                         ┆ str               ┆ i32                 │
╞═════════════════════════════╪═══════════════════╪═════════════════════╡
│ Base_donnees v5.xlsx        ┆ 1                 ┆ 1                   │
│ Base_donnees v5.xlsx        ┆ SITG_Adresse_EGID ┆ 0                   │
│ Base_donnees v5.xlsx        ┆ EGID_combustibles ┆ 0                   │
│ Base_donnees v5.xlsx        ┆ Chaudiere_annee   ┆ 0                   │
│ Base_donnees v5.xlsx        ┆ EGID_chaudière    ┆ 0                   │
│ …                           ┆ …                 ┆ …                   │
│ df_02_merge_adresses.xlsx   ┆ Sheet1            ┆ 0                   │
│ df_04_merge_analyse.xlsx    ┆ Sheet1            ┆ 0                   │
│ DERNIER_INDICE.xlsx         ┆ Sheet1            ┆ 0                   │
│ EGID_Adresses.xlsx          ┆ Feuil1            ┆ 0                   │
│ EGID_Adresses_original.xlsx ┆ Feuil1            ┆ 0                   │
└─────────────────────────────┴───────────────────┴─────────────────────┘

'Final shape: (5650758, 992)'

shape: (5_650_758, 992)
┌────────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬─────────┬───────────┐
│ Numéro int ┆ Installat ┆ numéro    ┆ Raison    ┆ … ┆ SITG_SCOR ┆ Addresse_ ┆ commune ┆ NPA-COMMU │
│ ervention  ┆ ion       ┆ partenair ┆ sociale   ┆   ┆ E         ┆ sans_NPA  ┆ ---     ┆ NE        │
│ ---        ┆ ---       ┆ e         ┆ ---       ┆   ┆ ---       ┆ ---       ┆ str     ┆ ---       │
│ str        ┆ str       ┆ ---       ┆ str       ┆   ┆ str       ┆ str       ┆         ┆ str       │
│            ┆           ┆ str       ┆           ┆   ┆           ┆           ┆         ┆           │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═════════╪═══════════╡
│ G0001      ┆ Grande    ┆ 1269817   ┆ Résidence ┆ … ┆ null      ┆ null      ┆ null    ┆ null      │
│            ┆           ┆           ┆ Jura      ┆   ┆           ┆           ┆         ┆           │
│ G0002      ┆ Grande    ┆ 1087032   ┆ EMS Franc ┆ … ┆ null      ┆ null      ┆ null    ┆ null      │
│            ┆           ┆           ┆ hises     ┆   ┆           ┆           ┆         ┆           │
│ G0003      ┆ Grande    ┆ 91228     ┆ Hôtel Tor ┆ … ┆ null      ┆ null      ┆ null    ┆ null      │
│ G0004      ┆ Grande    ┆ 1101205   ┆ Clinique  ┆ … ┆ null      ┆ null      ┆ null    ┆ null      │
│            ┆           ┆           ┆ de la     ┆   ┆           ┆           ┆         ┆           │
│            ┆           ┆           ┆ Plaine    ┆   ┆           ┆           ┆         ┆           │
│ G0005      ┆ Grande    ┆ 1156078   ┆ EMS les   ┆ … ┆ null      ┆ null      ┆ null    ┆ null      │
│            ┆           ┆           ┆ Mouilles  ┆   ┆           ┆           ┆         ┆           │
│ …          ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …       ┆ …         │
│ null       ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null    ┆ null      │
│ null       ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null    ┆ null      │
│ null       ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null    ┆ null      │
│ null       ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null    ┆ null      │
│ null       ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null    ┆ null      │
└────────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴─────────┴───────────┘

In [5]:
rue_cols: list[str] = [
    c for c in df_all.columns if ("rue" in c.lower() or "adresse" in c.lower())
]
# remove some columns that are not relevant
removed_cols: list[str] = [
    "Rue des Savoises, 15",
    "adresse facture 1",
    "adresse facture 2",
    "adresse facture 3",
    "adresse facture 4",
    "adresse facture 5",
    "adresse facture 6",
    "adresse facture 7",
    "analyse_adresse_inconnues",
    "analyse_adresse",
    "Adresse facturation",
    "Adresse LC",
]
rue_cols: list[str] = [c for c in rue_cols if c not in removed_cols]

print(rue_cols)

['Rue et numéro renseignés', 'rue SITG', 'ADRESSE', 'ADRESSE_BATIMENT', 'Rue et N°', 'Adresse SITG', 'adresse_spotfire', 'Adresse lieu de consommation', 'rue_et_nb', 'rue_et_nb_original', 'SITG_ADRESSE']

In [6]:
# Stack every rue/adresse column into a single column (vertical concat),
# then drop nulls. Each column is renamed to "adresse" first so they align
# under one name; order of columns/rows doesn't matter since we're just
# pooling all the non-null address values together.
df_adresse = (
    pl.concat(
        [df_all.select(pl.col(c).alias("adresse")) for c in rue_cols],
        how="vertical",
    )
    .drop_nulls()
    .unique()
)

print(f"Total non-null address values: {df_adresse.height}")
display(df_adresse)

Total non-null address values: 129968

shape: (129_968, 1)
┌───────────────────────────────┐
│ adresse                       │
│ ---                           │
│ str                           │
╞═══════════════════════════════╡
│ Rte de Saconnex-d'Arve 129    │
│ Chemin Agénor- PARMELIN, 3BIS │
│ Place du Temple, 1            │
│ Av. du Mervelet 14            │
│ Chemin des Rubiettes 16       │
│ …                             │
│ Route Jean-Jacques- RIGAUD, 8 │
│ Chemin de l'Eglise 2A         │
│ Route d' Annecy, 140          │
│ L'Ancienne-Route 54           │
│ Chemin des Rasses, 41         │
└───────────────────────────────┘

In [10]:
df_adresse_existant: DataFrame = pl.read_csv(
    source="../tests/test_adresses.csv"
).select(pl.col(name="Rue et N°").alias(name="adresse"))

display(df_adresse_existant)

shape: (107, 1)
┌────────────────────────────┐
│ adresse                    │
│ ---                        │
│ str                        │
╞════════════════════════════╡
│ 12 rue Jean-Charles Amat   │
│ 37, sous Garan             │
│ Ancienne route, 78         │
│ Av de Thonex 30            │
│ Av. Blanc, 5               │
│ …                          │
│ Ruelle du Midi 5           │
│ Vieux chemin d'Onex, 54    │
│ place Isaac Mercier, 1     │
│ rue Butini, 7              │
│ rue du Pré-du-Couvent 1bis │
└────────────────────────────┘

In [13]:
df_final: DataFrame = (
    pl.concat(items=[df_adresse_existant, df_adresse]).unique().drop_nulls()
)

display(df_final)

csv_name: str = (
    f"../tests/test_adresses_{datetime.now().strftime(format='%Y%m%d_%H%M%S')}.csv"
)

df_final.write_csv(file=csv_name, separator=";")

shape: (129_971, 1)
┌───────────────────────────────┐
│ adresse                       │
│ ---                           │
│ str                           │
╞═══════════════════════════════╡
│ Route de Frontenex 46         │
│ Chemin de Tattes-Fontaine, 43 │
│ Rue Ancienne 69               │
│ Rue des Peupliers, 24         │
│ Rte de La-Capite 173 A        │
│ …                             │
│ Route du Mandement 539        │
│ Ch. des Bélosses 9            │
│ Ch. de Delay 7                │
│ Chemin du Prunier, 10         │
│ Ch. de Mont-Rose 20           │
└───────────────────────────────┘